---
apiVersion: v1
kind: Pod
metadata:
  name: jenkins
spec:
  restartPolicy: OnFailure
  containers:
  - name: jenkins
    image: jenkins/jenkins
    resources:
      requests:
        memory: 100Mi
      limits:
        memory: 250Mi

# memory to 40 Mi to fail

---
apiVersion: v1
kind: Pod
metadata:
  name: jenkins1
spec:
  containers:
  - name: jenkins
    image: jenkins/jenkins
    resources:
      requests:
        memory: 40Mi
      limits:
        memory: 50Mi