---
apiVersion: v1
kind: Pod
metadata:
  name: jenkins2
spec:
  restartPolicy: OnFailure
  containers:
  - name: jenkins
    image: jenkins/jenkins
    resources:
      requests:
        memory: 100Mi
        cpu: 0.01
      limits:
        memory: 500Mi
        cpu: 0.05