# init cotainer willl be sucessfully completed and main container will start
---
apiVersion: v1
kind: Pod
metadata: 
  name: alpine
spec:
  containers:
  - name: alpine
    image: alpine
    command:
    - sleep
    - "1d"
  initContainers:
  - name: alpine
    image: alpine
    command:
    - sleep
    - "15s"