---
apiVersion: v1
kind: ReplicationController
metadata:
  name: test-rc
spec:
  minReadySeconds: 1
  replicas: 3
  selector:
    tier: backend
  template: 
    metadata:
      name: nginx
      labels:
        tier: end
    spec:
      containers:
      - name: nginx
        image: nginx