---
apiVersion: v1
kind: ReplicationController
metadata:
  name: sample-rc
spec:
  minReadySeconds: 1
  replicas: 3
  selector:
    matchLabels:
      tier: backend
  template: 
    metadata:
      name: nginx
      labels:
        tier: backend
    spec:
      containers:
        name: nginx
        image: nginx