---
apiVersion: v1
kind: Pod
metadata: 
  name: business
  lables:
    env: prod
    tier: backend
spec:
  containers:
  - name: nginx
    image: nginx


---
apiVersion: v1
kind: Pod
metadata: 
  name: web
  lables:
    env: prod
    tier: frontend
spec:
  containers:
  - name: httpd
    image: httpd